-- Create diverse League of Legends tournaments for testing
-- Various formats: Single/Double Elimination, Round Robin, different match formats

-- Tournament 1: Classic Single Elimination (Team Tournament) - Registration Open
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Spring Championship - Teams',
 'Premier team tournament featuring the best League of Legends teams. Single elimination bracket with Bo3 matches leading to a Bo5 final.',
 'league_of_legends',
 'single_elimination',
 'team',
 5,
 8,
 4,
 true,
 'anyone',
 'ranked',
 NOW() + INTERVAL '2 days',
 NOW() + INTERVAL '3 days',
 NOW() + INTERVAL '3 days' - INTERVAL '1 hour',
 'registration',
 '{"matchFormat": "bo3", "map": "summoners_rift", "draftType": "tournament_draft", "gameMode": "classic", "allowSubs": true, "maxSubs": 2}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW(),
 NOW());

-- Tournament 2: Double Elimination Showdown - Registration Open
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Double Elimination Gauntlet',
 'Competitive double elimination tournament. Everyone gets a second chance in the loser bracket!',
 'league_of_legends',
 'double_elimination',
 'team',
 5,
 8,
 2,
 true,
 'registered_only',
 'skill_balanced',
 NOW() + INTERVAL '5 days',
 NOW() + INTERVAL '6 days',
 NOW() + INTERVAL '6 days' - INTERVAL '2 hours',
 'registration',
 '{"matchFormat": "bo3", "map": "summoners_rift", "draftType": "tournament_draft", "gameMode": "classic", "allowSubs": true, "maxSubs": 1}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW(),
 NOW());

-- Tournament 3: Round Robin League - In Progress
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  started_at,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Round Robin Championship',
 'Every team plays every other team in this comprehensive round robin format. Best overall record wins!',
 'league_of_legends',
 'round_robin',
 'team',
 5,
 6,
 4,
 true,
 'anyone',
 'ranked',
 NOW() - INTERVAL '1 day',
 NOW() - INTERVAL '2 hours',
 NOW() - INTERVAL '3 hours',
 'in_progress',
 NOW() - INTERVAL '2 hours',
 '{"matchFormat": "bo1", "map": "summoners_rift", "draftType": "tournament_draft", "gameMode": "classic", "allowSubs": false, "roundRobinType": "single", "groupCreationMethod": "single_group"}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW() - INTERVAL '1 week',
 NOW());

-- Tournament 4: Fast-Paced Single Elim (Bo1) - Registration Open
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Lightning League - Bo1 Blitz',
 'Fast-paced single elimination tournament with Bo1 matches. Quick games, high stakes!',
 'league_of_legends',
 'single_elimination',
 'team',
 5,
 16,
 8,
 true,
 'anyone',
 'random',
 NOW() + INTERVAL '1 day',
 NOW() + INTERVAL '2 days',
 NOW() + INTERVAL '2 days' - INTERVAL '30 minutes',
 'registration',
 '{"matchFormat": "bo1", "map": "summoners_rift", "draftType": "blind_pick", "gameMode": "classic", "allowSubs": true, "maxSubs": 1}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW(),
 NOW());

-- Tournament 5: Elite Bo5 Championship - Registration Open
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Elite Championships - Bo5 Format',
 'The ultimate test of skill and endurance. All matches are Bo5 from start to finish.',
 'league_of_legends',
 'single_elimination',
 'team',
 5,
 8,
 6,
 true,
 'registered_only',
 'ai_optimized',
 NOW() + INTERVAL '4 days',
 NOW() + INTERVAL '7 days',
 NOW() + INTERVAL '7 days' - INTERVAL '1 hour',
 'registration',
 '{"matchFormat": "bo5", "map": "summoners_rift", "draftType": "tournament_draft", "gameMode": "classic", "allowSubs": true, "maxSubs": 2}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW(),
 NOW());

-- Tournament 6: Completed Tournament (for history)
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  started_at,
  completed_at,
  completion_reason,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Winter Finals 2024',
 'The epic conclusion to our winter season. Completed tournament showcasing the best teams.',
 'league_of_legends',
 'double_elimination',
 'team',
 5,
 8,
 8,
 true,
 'anyone',
 'ranked',
 NOW() - INTERVAL '10 days',
 NOW() - INTERVAL '8 days',
 NOW() - INTERVAL '8 days' - INTERVAL '1 hour',
 'completed',
 NOW() - INTERVAL '8 days',
 NOW() - INTERVAL '5 days',
 'natural',
 '{"matchFormat": "bo3", "map": "summoners_rift", "draftType": "tournament_draft", "gameMode": "classic", "allowSubs": true, "maxSubs": 2}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW() - INTERVAL '2 weeks',
 NOW() - INTERVAL '5 days');

-- Tournament 7: Password Protected Elite Tournament
INSERT INTO tournaments (
  id,
  name,
  description,
  game,
  format,
  tournament_type,
  team_size,
  max_participants,
  current_participants,
  password_hash,
  is_public,
  participation_type,
  seeding_type,
  registration_deadline,
  start_time,
  check_in_deadline,
  status,
  settings,
  creator_id,
  created_at,
  updated_at
) VALUES
(gen_random_uuid(),
 'Invitation Only Championship',
 'Private elite tournament for invited teams only. Password required for registration.',
 'league_of_legends',
 'double_elimination',
 'team',
 5,
 4,
 0,
 '$2a$10$abcdefghijklmnopqrstuvwxyz', -- Hashed 'elite2024'
 false,
 'registered_only',
 'manual',
 NOW() + INTERVAL '3 days',
 NOW() + INTERVAL '5 days',
 NOW() + INTERVAL '5 days' - INTERVAL '1 hour',
 'registration',
 '{"matchFormat": "bo5", "map": "summoners_rift", "draftType": "tournament_draft", "gameMode": "classic", "allowSubs": false}',
 '29d037fe-e67f-4164-a5ab-2c926719485c',
 NOW(),
 NOW());

-- Verify tournaments were created
SELECT 'Created Tournaments:' as info;
SELECT
  name,
  format,
  settings->>'matchFormat' as match_format,
  tournament_type,
  max_participants,
  current_participants,
  status,
  start_time::date as start_date
FROM tournaments
WHERE game = 'league_of_legends'
  AND creator_id = '29d037fe-e67f-4164-a5ab-2c926719485c'
ORDER BY created_at DESC;